#!/usr/bin/env python3
"""inject_sri.py — compute + inject SRI hashes for every same-origin asset.

For every <link rel="stylesheet" href="X.css"> and <script src="Y.js">
in the HTML files under static/, compute SHA-384(asset bytes) and
inject `integrity="sha384-..."` (idempotent: re-runs match-and-skip).

Same-origin only — external https:// URLs are out of scope (defense
against compromised CDN is a separate concern: the operator has to
fetch the SRI hash from the CDN's release notes once and pin it).

If the file referenced is missing, prints a warning and skips
(unbuilt_route phase already strict-fails missing assets).
"""
import base64
import hashlib
import os
import re
import sys

STATIC = "/tmp/skillshots-poc/static"

# Files that are regenerated by every forge build. Skipping their
# SRI keeps the dev loop fast (no need to re-inject after every
# build); production should drop these tags entirely.
EXCLUDE = {
    "forge-findings.js",  # rewritten by forge.sh on every run
}


def sri_hash(path: str) -> str | None:
    try:
        with open(path, "rb") as f:
            digest = hashlib.sha384(f.read()).digest()
        return "sha384-" + base64.b64encode(digest).decode("ascii")
    except FileNotFoundError:
        return None


# Match <link rel="stylesheet" href="..."> OR <script ... src="...">
# preserving the rest of the tag verbatim.
LINK_RE = re.compile(
    r'(<link\b[^>]*rel="stylesheet"[^>]*href=")([^"]+)("([^>]*?)>)',
    re.I,
)
SCRIPT_RE = re.compile(
    r'(<script\b[^>]*src=")([^"]+)("([^>]*?)>)',
    re.I,
)


def inject_one(html: str) -> tuple[str, int]:
    changes = 0

    def handle(m: re.Match, kind: str) -> str:
        nonlocal changes
        prefix, href, suffix, rest = m.group(1), m.group(2), m.group(3), m.group(4)
        full = m.group(0)
        # Skip absolute / external URLs.
        if href.startswith(("http://", "https://", "//")):
            return full
        # Skip transient files (regenerated by forge each build).
        if os.path.basename(href.lstrip("/")) in EXCLUDE:
            return full
        # Resolve to disk path.
        local = href.lstrip("/")
        disk = os.path.join(STATIC, local)
        h = sri_hash(disk)
        if h is None:
            sys.stderr.write(f"  warn: missing asset {disk} for href={href}\n")
            return full
        # If integrity= is already present AND matches the disk
        # hash, no change. If it's present but stale (file changed
        # since last inject), REPLACE it. Critical 2026-05-04: not
        # refreshing stale hashes makes the browser refuse the asset
        # and the page renders unstyled.
        existing = re.search(r'integrity="(sha384-[A-Za-z0-9+/=]+)"', full)
        if existing:
            if existing.group(1) == h:
                return full
            # Replace stale integrity with fresh one.
            updated = re.sub(
                r'integrity="sha384-[A-Za-z0-9+/=]+"',
                f'integrity="{h}"',
                full,
            )
            changes += 1
            return updated
        # No integrity yet — insert it before the closing '>'.
        changes += 1
        new_rest = rest.rstrip()
        return (
            prefix + href + suffix.replace(rest + ">", "")
            + new_rest + f' integrity="{h}" crossorigin="anonymous">'
        )

    html = LINK_RE.sub(lambda m: handle(m, "link"), html)
    html = SCRIPT_RE.sub(lambda m: handle(m, "script"), html)
    return html, changes


def main() -> int:
    total = 0
    files = 0
    for fn in sorted(os.listdir(STATIC)):
        if not fn.endswith(".html"):
            continue
        path = os.path.join(STATIC, fn)
        with open(path, encoding="utf-8") as f:
            src = f.read()
        new_src, n = inject_one(src)
        if n > 0:
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_src)
            print(f"  {fn}: injected {n} SRI hash(es)")
            total += n
            files += 1
        else:
            print(f"  {fn}: 0 (already done or no eligible tags)")
    print(f"injected {total} hashes across {files} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
