//! `manifest-codegen` — build-time projector.
//!
//! Per `PLATFORM_ROADMAP.md` §3 + the
//! `manifest_layer_is_the_keystone` doctrine, every downstream
//! consumer (`forge-cli` / `forge-phases` / `forge-serve` /
//! `server-stub` / admin UI) reads a `PlatformManifest` once at
//! build time and gets typed Rust constants in return.
//!
//! Usage from a downstream crate's `build.rs`:
//!
//! ```no_run
//! fn main() {
//!     manifest_codegen::generate_from_file("manifest.toml")
//!         .expect("manifest codegen failed");
//! }
//! ```
//!
//! Then in `src/lib.rs`:
//!
//! ```ignore
//! include!(concat!(env!("OUT_DIR"), "/manifest_generated.rs"));
//!
//! // Now in scope:
//! //   pub const ALL_CAPABILITIES: &[CapabilityRecord] = &[...];
//! //   pub const ALL_PHASES:       &[PhaseRecord]      = &[...];
//! //   pub const ALL_BACKENDS:     &[BackendRecord]    = &[...];
//! //   pub const MANIFEST_SCHEMA:  &str                = "1";
//! //   pub const MANIFEST_PLATFORM:&str                = "plausiden";
//! ```
//!
//! ### Why a build.rs projector instead of a proc-macro?
//!
//! A proc-macro would force every consumer to depend on a
//! compiler-host crate that re-runs whenever the macro input
//! changes. A build.rs projector:
//!   - reads the manifest once per crate per build
//!   - emits plain `&'static [...]` slices the optimizer collapses
//!   - prints `cargo:rerun-if-changed=...` so manifest edits
//!     trigger only the affected crate, not the whole graph
//!   - keeps the consumer crate's compile graph small (no syn /
//!     quote pulled in transitively).
//!
//! A future proc-macro layer (task #30b) can land on top once
//! we have concrete use cases for compile-time expansion
//! beyond constant projection.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

use std::fs;
use std::path::{Path, PathBuf};

use manifest_core::{ManifestError, PlatformManifest};

/// Errors returned by the codegen entry points.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    /// Failed to read the manifest file.
    #[error("failed to read manifest at {path}: {source}")]
    Read {
        /// The path that failed to read.
        path: PathBuf,
        /// The underlying IO error.
        #[source]
        source: std::io::Error,
    },
    /// Failed to parse the manifest contents.
    #[error("manifest parse failed: {0}")]
    Parse(#[from] ManifestError),
    /// Failed to write the generated file.
    #[error("failed to write generated.rs to {path}: {source}")]
    Write {
        /// The path that failed to write.
        path: PathBuf,
        /// The underlying IO error.
        #[source]
        source: std::io::Error,
    },
    /// `OUT_DIR` was not set (build.rs precondition).
    #[error("OUT_DIR env var not set — codegen must be called from build.rs")]
    NoOutDir,
}

/// Read `path`, parse as TOML, project into Rust source, write to
/// `$OUT_DIR/manifest_generated.rs`. Emits the cargo rerun-if
/// directive.
///
/// Call from `build.rs`.
pub fn generate_from_file(path: impl AsRef<Path>) -> Result<(), CodegenError> {
    let path = path.as_ref();
    let src = fs::read_to_string(path).map_err(|e| CodegenError::Read {
        path: path.to_path_buf(),
        source: e,
    })?;
    let manifest = PlatformManifest::from_toml(&src)?;
    let out_dir = std::env::var_os("OUT_DIR").ok_or(CodegenError::NoOutDir)?;
    let out_path: PathBuf = PathBuf::from(out_dir).join("manifest_generated.rs");
    let generated = project_to_rust(&manifest);
    fs::write(&out_path, generated).map_err(|e| CodegenError::Write {
        path: out_path,
        source: e,
    })?;
    println!("cargo:rerun-if-changed={}", path.display());
    Ok(())
}

/// Project a manifest into the Rust source string that
/// `generate_from_file` would write. Public so tests + tooling can
/// exercise the projection without touching the filesystem.
pub fn project_to_rust(manifest: &PlatformManifest) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by manifest-codegen. Do not edit by hand.\n");
    out.push_str("// Regenerate by editing manifest.toml + rebuilding.\n\n");

    out.push_str("/// Schema version of the manifest this was generated from.\n");
    out.push_str(&format!(
        "pub const MANIFEST_SCHEMA: &str = {};\n\n",
        escape_string_literal(&manifest.schema_version),
    ));

    out.push_str("/// Platform identifier from the manifest.\n");
    out.push_str(&format!(
        "pub const MANIFEST_PLATFORM: &str = {};\n\n",
        escape_string_literal(&manifest.platform),
    ));

    out.push_str("/// Single capability record. Mirrors manifest_core::Capability.\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct CapabilityRecord {\n");
    out.push_str("    /// kebab-case capability ID.\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    /// One-line human summary.\n");
    out.push_str("    pub summary: &'static str,\n");
    out.push_str("    /// Subsystem slug (forge/loom/crawler/annotator/cms).\n");
    out.push_str("    pub ownership: &'static str,\n");
    out.push_str("    /// Handler module references.\n");
    out.push_str("    pub handlers: &'static [&'static str],\n");
    out.push_str("    /// UI references.\n");
    out.push_str("    pub ui: &'static [&'static str],\n");
    out.push_str("    /// Test references.\n");
    out.push_str("    pub tests: &'static [&'static str],\n");
    out.push_str("    /// Doc references.\n");
    out.push_str("    pub docs: &'static [&'static str],\n");
    out.push_str("}\n\n");

    out.push_str("/// Every capability declared in the manifest.\n");
    out.push_str("pub const ALL_CAPABILITIES: &[CapabilityRecord] = &[\n");
    for cap in &manifest.capabilities {
        out.push_str("    CapabilityRecord {\n");
        out.push_str(&format!(
            "        id: {},\n",
            escape_string_literal(cap.id.as_str())
        ));
        out.push_str(&format!(
            "        summary: {},\n",
            escape_string_literal(&cap.summary)
        ));
        out.push_str(&format!(
            "        ownership: {},\n",
            escape_string_literal(cap.ownership.slug())
        ));
        out.push_str("        handlers: &[");
        push_str_slice(&mut out, cap.handlers.iter().map(|h| h.0.as_str()));
        out.push_str("],\n");
        out.push_str("        ui: &[");
        push_str_slice(&mut out, cap.ui.iter().map(|u| u.0.as_str()));
        out.push_str("],\n");
        out.push_str("        tests: &[");
        push_str_slice(&mut out, cap.tests.iter().map(|t| t.0.as_str()));
        out.push_str("],\n");
        out.push_str("        docs: &[");
        push_str_slice(&mut out, cap.docs.iter().map(|d| d.0.as_str()));
        out.push_str("],\n");
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");

    out.push_str("/// Single phase record. Mirrors manifest_core::PhaseDescriptor.\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct PhaseRecord {\n");
    out.push_str("    /// kebab-case phase ID.\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    /// Capability this phase implements (`\"\"` if none).\n");
    out.push_str("    pub implements: &'static str,\n");
    out.push_str("    /// One-line summary.\n");
    out.push_str("    pub summary: &'static str,\n");
    out.push_str("    /// Default severity slug (info/warn/strict).\n");
    out.push_str("    pub default_severity: &'static str,\n");
    out.push_str("    /// Phase IDs this one depends on.\n");
    out.push_str("    pub depends_on: &'static [&'static str],\n");
    out.push_str("}\n\n");

    out.push_str("/// Every phase declared in the manifest.\n");
    out.push_str("pub const ALL_PHASES: &[PhaseRecord] = &[\n");
    for p in &manifest.phases {
        out.push_str("    PhaseRecord {\n");
        out.push_str(&format!(
            "        id: {},\n",
            escape_string_literal(p.id.as_str())
        ));
        out.push_str(&format!(
            "        implements: {},\n",
            escape_string_literal(p.implements.as_ref().map(|c| c.as_str()).unwrap_or(""))
        ));
        out.push_str(&format!(
            "        summary: {},\n",
            escape_string_literal(&p.summary)
        ));
        out.push_str(&format!(
            "        default_severity: {},\n",
            escape_string_literal(severity_slug(p.default_severity))
        ));
        out.push_str("        depends_on: &[");
        push_str_slice(&mut out, p.depends_on.iter().map(|c| c.as_str()));
        out.push_str("],\n");
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");

    out.push_str("/// Single backend record. Mirrors manifest_core::BackendDescriptor.\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct BackendRecord {\n");
    out.push_str("    /// kebab-case backend ID.\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    /// Capability this backend implements (`\"\"` if none).\n");
    out.push_str("    pub implements: &'static str,\n");
    out.push_str("    /// One-line summary.\n");
    out.push_str("    pub summary: &'static str,\n");
    out.push_str("    /// Route path (`\"\"` if none).\n");
    out.push_str("    pub route: &'static str,\n");
    out.push_str("    /// HTTP method (`\"\"` if none).\n");
    out.push_str("    pub method: &'static str,\n");
    out.push_str("}\n\n");

    out.push_str("/// Every backend declared in the manifest.\n");
    out.push_str("pub const ALL_BACKENDS: &[BackendRecord] = &[\n");
    for b in &manifest.backends {
        out.push_str("    BackendRecord {\n");
        out.push_str(&format!(
            "        id: {},\n",
            escape_string_literal(b.id.as_str())
        ));
        out.push_str(&format!(
            "        implements: {},\n",
            escape_string_literal(b.implements.as_ref().map(|c| c.as_str()).unwrap_or(""))
        ));
        out.push_str(&format!(
            "        summary: {},\n",
            escape_string_literal(&b.summary)
        ));
        out.push_str(&format!(
            "        route: {},\n",
            escape_string_literal(b.route.as_deref().unwrap_or(""))
        ));
        out.push_str(&format!(
            "        method: {},\n",
            escape_string_literal(b.method.as_deref().unwrap_or(""))
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");

    out.push_str(LOOKUP_HELPERS);

    out
}

/// Generic lookup helpers projected into every consumer crate.
///
/// All functions are O(N) linear scans — the typical manifest has
/// <100 entries so a scan is faster than the constants needed for
/// a perfect-hash table.
const LOOKUP_HELPERS: &str = r#"
/// Find a capability record by ID. Returns `None` when no record
/// matches. O(N) linear scan over `ALL_CAPABILITIES`.
#[must_use]
pub fn find_capability_by_id(id: &str) -> Option<&'static CapabilityRecord> {
    ALL_CAPABILITIES.iter().find(|c| c.id == id)
}

/// Find a phase record by ID. Returns `None` when no record matches.
#[must_use]
pub fn find_phase_by_id(id: &str) -> Option<&'static PhaseRecord> {
    ALL_PHASES.iter().find(|p| p.id == id)
}

/// Find a backend record by ID. Returns `None` when no record matches.
#[must_use]
pub fn find_backend_by_id(id: &str) -> Option<&'static BackendRecord> {
    ALL_BACKENDS.iter().find(|b| b.id == id)
}

/// Iterator over every phase record whose `implements` field equals
/// the given capability ID. Empty when the capability has no phases.
pub fn phases_for_capability<'a>(
    capability_id: &'a str,
) -> impl Iterator<Item = &'static PhaseRecord> + 'a {
    ALL_PHASES.iter().filter(move |p| p.implements == capability_id)
}

/// Iterator over every backend record whose `implements` field equals
/// the given capability ID. Empty when the capability has no backends.
pub fn backends_for_capability<'a>(
    capability_id: &'a str,
) -> impl Iterator<Item = &'static BackendRecord> + 'a {
    ALL_BACKENDS.iter().filter(move |b| b.implements == capability_id)
}

/// True iff a capability with the given ID exists.
#[must_use]
pub fn capability_exists(id: &str) -> bool {
    find_capability_by_id(id).is_some()
}

/// True iff a backend with the given (method, route) pair exists in
/// the manifest. Useful for codegen of route tables — answer
/// "is this route declared?" without building a HashMap.
#[must_use]
pub fn backend_with_route(method: &str, route: &str) -> Option<&'static BackendRecord> {
    ALL_BACKENDS
        .iter()
        .find(|b| b.method == method && b.route == route)
}
"#;

fn severity_slug(s: manifest_core::DefaultSeverity) -> &'static str {
    match s {
        manifest_core::DefaultSeverity::Info => "info",
        manifest_core::DefaultSeverity::Warn => "warn",
        manifest_core::DefaultSeverity::Strict => "strict",
    }
}

fn push_str_slice<'a>(out: &mut String, items: impl Iterator<Item = &'a str>) {
    let mut first = true;
    for s in items {
        if !first {
            out.push_str(", ");
        }
        first = false;
        out.push_str(&escape_string_literal(s));
    }
}

/// Escape a string as a Rust `&'static str` literal. The output
/// includes the surrounding double quotes. Handles `\`, `"`, and
/// control characters per Rust string-literal grammar.
fn escape_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use manifest_core::{
        Capability, CapabilityId, DefaultSeverity, DocRef, HandlerRef, Ownership, PhaseDescriptor,
        PlatformManifest, TestRef, UiRef,
    };

    fn sample_manifest() -> PlatformManifest {
        PlatformManifest {
            platform: "plausiden".into(),
            schema_version: "1".into(),
            capabilities: vec![Capability {
                id: CapabilityId::parse("auth").unwrap(),
                summary: "user auth".into(),
                ownership: Ownership::Forge,
                handlers: vec![HandlerRef("forge-phases::auth".into())],
                ui: vec![UiRef("cms-admin::auth".into())],
                tests: vec![TestRef("forge-phases::auth::tests::ok".into())],
                docs: vec![DocRef("docs/auth.md".into())],
                metadata: BTreeMap::new(),
            }],
            phases: vec![PhaseDescriptor {
                id: CapabilityId::parse("p-auth").unwrap(),
                implements: Some(CapabilityId::parse("auth").unwrap()),
                summary: "auth phase".into(),
                default_severity: DefaultSeverity::Strict,
                depends_on: vec![],
            }],
            backends: vec![],
            ..Default::default()
        }
    }

    #[test]
    fn project_emits_header_constants() {
        let m = sample_manifest();
        let src = project_to_rust(&m);
        assert!(src.contains("AUTO-GENERATED"));
        assert!(src.contains("pub const MANIFEST_SCHEMA: &str = \"1\";"));
        assert!(src.contains("pub const MANIFEST_PLATFORM: &str = \"plausiden\";"));
    }

    #[test]
    fn project_includes_capability_record() {
        let m = sample_manifest();
        let src = project_to_rust(&m);
        assert!(src.contains("ALL_CAPABILITIES"));
        assert!(src.contains("\"auth\""));
        assert!(src.contains("\"user auth\""));
        assert!(src.contains("\"forge\""));
        assert!(src.contains("\"forge-phases::auth\""));
    }

    #[test]
    fn project_includes_phase_record_with_severity() {
        let m = sample_manifest();
        let src = project_to_rust(&m);
        assert!(src.contains("ALL_PHASES"));
        assert!(src.contains("\"p-auth\""));
        assert!(src.contains("default_severity: \"strict\""));
        assert!(src.contains("implements: \"auth\""));
    }

    #[test]
    fn project_empty_manifest_emits_empty_slices() {
        let m = PlatformManifest {
            platform: "p".into(),
            ..Default::default()
        };
        let src = project_to_rust(&m);
        assert!(src.contains("ALL_CAPABILITIES: &[CapabilityRecord] = &[\n];"));
        assert!(src.contains("ALL_PHASES: &[PhaseRecord] = &[\n];"));
        assert!(src.contains("ALL_BACKENDS: &[BackendRecord] = &[\n];"));
    }

    #[test]
    fn project_emits_lookup_helpers() {
        let m = sample_manifest();
        let src = project_to_rust(&m);
        assert!(src.contains("pub fn find_capability_by_id"));
        assert!(src.contains("pub fn find_phase_by_id"));
        assert!(src.contains("pub fn find_backend_by_id"));
        assert!(src.contains("pub fn phases_for_capability"));
        assert!(src.contains("pub fn backends_for_capability"));
        assert!(src.contains("pub fn capability_exists"));
        assert!(src.contains("pub fn backend_with_route"));
    }

    #[test]
    fn empty_manifest_still_emits_lookup_helpers() {
        let m = PlatformManifest {
            platform: "p".into(),
            ..Default::default()
        };
        let src = project_to_rust(&m);
        assert!(src.contains("find_capability_by_id"));
        assert!(src.contains("backend_with_route"));
    }

    #[test]
    fn escape_handles_special_chars() {
        assert_eq!(escape_string_literal("hi"), "\"hi\"");
        assert_eq!(escape_string_literal("a\"b"), "\"a\\\"b\"");
        assert_eq!(escape_string_literal("a\\b"), "\"a\\\\b\"");
        assert_eq!(escape_string_literal("a\nb"), "\"a\\nb\"");
    }

    #[test]
    fn generate_from_file_writes_to_out_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let manifest_path = tmp.path().join("manifest.toml");
        std::fs::write(
            &manifest_path,
            r#"
platform = "plausiden"
schema-version = "1"
"#,
        )
        .unwrap();
        let out_dir = tempfile::tempdir().unwrap();
        std::env::set_var("OUT_DIR", out_dir.path());
        generate_from_file(&manifest_path).unwrap();
        let gen_path = out_dir.path().join("manifest_generated.rs");
        let src = std::fs::read_to_string(gen_path).unwrap();
        assert!(src.contains("AUTO-GENERATED"));
        assert!(src.contains("MANIFEST_PLATFORM"));
    }

    #[test]
    fn generate_from_file_reports_missing_file() {
        let out_dir = tempfile::tempdir().unwrap();
        std::env::set_var("OUT_DIR", out_dir.path());
        let err = generate_from_file("/nonexistent/manifest.toml").unwrap_err();
        assert!(matches!(err, CodegenError::Read { .. }));
    }
}
